name: Create an S3 Bucket using Terraform in AWS

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
     - name: code checkout
       uses: actions/checkout@v4
     - name: configure aws credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
     - name: install terraform 
       uses: hashicorp/setup-terraform@v3
     - name: initialize terraform 
       run: terraform init
     - name: terraform fmt
       uses: dflook/terraform-fmt-check@v1
       id: fmt-check
       with:
          path: my-terraform-config

     - name: Wrong formatting found
       if: ${{ failure() && steps.fmt-check.outputs.failure-reason == 'check-failed' }}
       run: echo "formatting check failed"
      
        
 
 

